Repository bootscore/bootscore, pull requests merged in 2023-12, with the labels that each got.

#645 Rewrite main.scss
  scss/_bscore_maps.scss
  scss/_bscore_utilities.scss
  scss/main.scss
Labels: documentation, feature, child

#654 Remove wpsites_query function limit to 24 items in loop
  functions.php
  inc/loop.php
  woocommerce/loop/loop-start.php
Labels: documentation

#647 Reduce compiled css file size
  scss/bootscore_woocommerce/_wc_ajax_cart.scss
  scss/bootscore_woocommerce/_wc_breadcrumb.scss
  scss/bootscore_woocommerce/_wc_buttons.scss
  scss/bootscore_woocommerce/_wc_cart.scss
  scss/bootscore_woocommerce/_wc_checkout.scss
  scss/bootscore_woocommerce/_wc_colors.scss
  scss/bootscore_woocommerce/_wc_form_login.scss
  scss/bootscore_woocommerce/_wc_forms.scss
  scss/bootscore_woocommerce/_wc_loop.scss
  scss/bootscore_woocommerce/_wc_product_single.scss
  scss/bootscore_woocommerce/_wc_qty_btn.scss
  scss/bootscore_woocommerce/_wc_sale_badge.scss
  scss/bootscore_woocommerce/_wc_shipping.scss
  scss/bootscore_woocommerce/_wc_tables.scss
  woocommerce/inc/wc-forms.php
  woocommerce/inc/wc-loop.php
  woocommerce/js/woocommerce.js
Labels: WooCommerce
