Repository bootscore/bootscore, pull requests merged in 2024-02, with the labels that each got.

#678 Revert "Fix wc 8.5 alerts"
  scss/bootscore_woocommerce/_wc_ajax_cart.scss
  scss/bootscore_woocommerce/_wc_alerts.scss
  scss/bootscore_woocommerce/_wc_deprecated.scss
  woocommerce/cart/mini-cart.php
  woocommerce/inc/ajax-add-to-cart.php
  woocommerce/notices/error.php
  woocommerce/notices/notice.php
  woocommerce/notices/success.php
Labels: WooCommerce

#675 Add theme support for block template-parts
  inc/theme-setup.php
Labels: Gutenberg

#575 Filter refactor
  404.php
  archive.php
  footer.php
  functions.php
  header.php
  inc/blocks/block-widget-archives.php
  inc/blocks/block-widget-calendar.php
  inc/blocks/block-widget-categories.php
  inc/blocks/block-widget-latest-comments.php
  inc/blocks/block-widget-latest-posts.php
  inc/blocks/block-widget-search.php
  inc/columns.php
  inc/container.php
  inc/deprecated.php
  inc/enqueue.php
  inc/scss-compiler.php
  inc/theme-setup.php
  index.php
  page-templates/page-blank-with-container.php
  page-templates/page-full-width-image.php
  page-templates/page-sidebar-left.php
  page-templates/page-sidebar-none.php
  page.php
  search.php
  sidebar.php
  single-templates/single-full-width-image.php
  single-templates/single-sidebar-left.php
  single-templates/single-sidebar-none.php
  single.php
  template-parts/header/offcanvas-woocommerce.php
  template-parts/header/top-nav-search-collapse-woocommerce.php
  template-parts/header/top-nav-search-collapse.php
  woocommerce.php
  woocommerce/content-product.php
Labels: documentation, feature, breaking

#705 Add top-bar widget position
  header.php
  inc/widgets.php
Labels: feature

#703 WC Ajax Mini Cart Quantity Buttons
  woocommerce/cart/mini-cart.php
  woocommerce/inc/ajax-add-to-cart.php
  woocommerce/inc/wc-mini-cart.php
  woocommerce/inc/wc-qty-btn.php
  woocommerce/js/woocommerce.js
Labels: feature, WooCommerce, ajax cart
